"""Incorrect restaurant_category helper table name

Revision ID: 2058315f4f03
Revises: abfdf7279561
Create Date: 2022-03-28 12:03:24.749352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2058315f4f03'
down_revision = 'abfdf7279561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_category',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'category_id')
    )
    op.drop_table('restaurant category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant category',
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='restaurant category_category_id_fkey'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='restaurant category_restaurant_id_fkey'),
    sa.PrimaryKeyConstraint('restaurant_id', 'category_id', name='restaurant category_pkey')
    )
    op.drop_table('restaurant_category')
    # ### end Alembic commands ###
