"""empty message

Revision ID: a97b1d460005
Revises: c03ce64d9dd6
Create Date: 2022-03-30 11:43:47.813317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97b1d460005'
down_revision = 'c03ce64d9dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('restaurant_user_id_fkey', 'restaurant', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant', 'account', ['account_id'], ['id'])
    op.drop_column('restaurant', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key('restaurant_user_id_fkey', 'restaurant', 'account', ['user_id'], ['id'])
    op.drop_column('restaurant', 'account_id')
    # ### end Alembic commands ###
