"""change user table name, it was a reserved keyword

Revision ID: c03ce64d9dd6
Revises: ec2a6e2adfde
Create Date: 2022-03-30 11:36:27.576132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03ce64d9dd6'
down_revision = 'ec2a6e2adfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('restaurant_user_id_fkey', 'restaurant', type_='foreignkey')
    op.drop_table('user')
    op.create_foreign_key(None, 'restaurant', 'account', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key('restaurant_user_id_fkey', 'restaurant', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('name', name='user_name_key')
    )
    op.drop_table('account')
    # ### end Alembic commands ###
